FROM digitalrebar/deploy-service-wrapper
MAINTAINER Victor Lowther <victor@rackn.com>

ARG DR_TAG

ENV SQUID_CACHE_DIR=/var/spool/squid3 \
    SQUID_LOG_DIR=/var/log/squid3 \
    SQUID_USER=proxy

COPY squid /tmp/squid

RUN apt-get update \
  && apt-get -y install squid3 squid-langpack \
  && dpkg --install /tmp/squid/squid-common_3.5.12-1ubuntu8_all.deb \
  && dpkg --install /tmp/squid/squid_3.5.12-1ubuntu8_amd64.deb \
  && dpkg --install /tmp/squid/squidclient_3.5.12-1ubuntu8_amd64.deb \
  && mv /etc/squid3/squid.conf /etc/squid3/squid.conf.dist

COPY squid.conf /tmp/squid.conf
COPY entrypoint.d/*.sh /usr/local/entrypoint.d/

ENTRYPOINT ["/sbin/docker-entrypoint.sh"]
